alwaysRunPostSteps: false
appium: false
autosplit: true
betaFeature:
    setPartiallyCompletedAsCompleted: false
cacheDirectories:
    - ./.gradle
cacheKey: '{{ checksum "build.gradle" }}'
captureScreenRecordingForScenarios: false
codeDirectory: hyperexecute-spock-sample
collectLocalGitData: true
combineTasksInMatrixMode: false
concurrency: 4
cypress: false
differentialUpload:
    enabled: false
    forcedDisabled: false
    ttlHours: null
dynamicAllocation: false
errorCategorizedOnFailureOnly: false
framework:
    additional_args: null
    args:
        appId: ""
        appPath: ""
        avoidAppLaunch: false
        deviceSelectionStrategy: ""
        devices: []
        disableReleaseDevice: false
        filters:
            attributes: []
        fixedIP: ""
        isRealMobile: false
        isVirtualDevice: false
        language: ""
        locale: ""
        minorOsVersion: false
        mitmProxy: false
        mobileDC: null
        networkHar: false
        platformName: ""
        playwrightRD: false
        preservedDevice: false
        queueTimeout: 0
        resignApp: true
        shards:
            mappings: []
        skipInstall: false
        skipUninstallPreviousBuild: false
        skipXMLOnRun: false
        testSuiteAppId: ""
        testSuitePath: ""
        uninstallPreviousBuild: false
        xcTestPlanId: ""
        xcTestPlanPath: ""
    baseCommand: ""
    defaultReports: false
    discoveryFlags: []
    discoveryMode: ""
    discoveryType: ""
    downloadURL: ""
    flags: []
    isTestNGXMLSuite: false
    licenseKey: ""
    name: ""
    runnerFlags: []
    toscaArgs: null
    userdefinediscovery: false
    version: ""
    workingDirectory: ""
globalTimeout: 150
jobID: ff84fbd4-0467-4f24-a5d6-dc24d501262f
key: 7HzTZNYQr2ODUvr3XO4iXdVfQPRRZcYIEeRiGsQxD9Ndva763B
localHTTPProxy: ""
maxRetriesPreSteps: 0
meta: {}
platformConfig: null
postDirectives:
    commands: []
    shell: ""
    workingDirectory: ""
pre:
    - gradlew clean build
preDirectives:
    commands:
        - gradlew clean build
    maxRetries: 0
    shell: ""
    workingDirectory: ""
project:
    id: ""
    name: ""
    type: default
regionConfig: []
runson: win
runtime:
    language: java
    version: "21"
    addons: []
    opts: {}
sourcePayload:
    verifySSL: true
storageType: ""
testDiscovery:
    autosubset: true
    command: for i in {1..${HYE_CONCURRENCY}}; do echo 'runLambda'; done
    mode: dynamic
    shell: bash
    type: raw
testDiscoveryResultV3: []
testRunnerCommand: ./gradlew $test
testSuiteStep: 150
testSuiteTimeout: 150
testSuites: []
triggerMode: false
tunnelOpts:
    testsPerTunnel: 10
user: linpaws13
version: "0.1"
waitForArtefactsUpload: false
